import test from 'node:test';
import assert from 'node:assert/strict';
import { createResendAdapter } from '../../functions/api/forms.ts';
const env={RESEND_SEND_API_KEY:'test-key',RESEND_FROM:'Joaquim Mota <geral@mail.joaquimmota.pt>',RESEND_REPLY_TO:'jrmota@kwportugal.pt',FORMS_RECIPIENT:'jrmota@kwportugal.pt'};
const lead={formType:'mortgage',route:'/credito-habitacao',idempotencyKey:'routing-test-001',fields:{firstName:'Ana Maria',lastName:'Costa Silva',name:'Ana Maria Costa Silva',email:'ana@example.test',phone:'900000000',consent:true}};
function transport(receipt={data:[{id:'consultant-id'},{id:'customer-id'}]}){const calls=[];return {calls,adapter:createResendAdapter(async(url,init)=>{calls.push({url,headers:init.headers,body:JSON.parse(init.body)});return new Response(JSON.stringify(receipt),{status:200})})}}
test('test mode redirects both emails exclusively to test recipient including mortgage',async()=>{const t=transport();const result=await t.adapter.notifyLead(lead,env);assert.equal(result.providerId,'consultant-id,customer-id');assert.equal(t.calls.length,1);assert.equal(t.calls[0].url,'https://api.resend.com/emails/batch');for(const mail of t.calls[0].body){assert.deepEqual(mail.to,['t@doop.pt']);assert.equal(mail.reply_to,'jrmota@kwportugal.pt');assert.equal(mail.from,env.RESEND_FROM)}assert.match(t.calls[0].body[0].text,/Nome: Ana Maria/);assert.match(t.calls[0].body[0].text,/Apelido: Costa Silva/);assert.doesNotMatch(t.calls[0].body[0].text,/Olá Mota/)});
test('live mortgage includes authorized credit recipient and customer separately',async()=>{const t=transport();await t.adapter.notifyLead(lead,{...env,FORMS_DELIVERY_MODE:'live'});assert.deepEqual(t.calls[0].body[0].to,['jrmota@kwportugal.pt','da@somoscredito.pt']);assert.deepEqual(t.calls[0].body[1].to,['ana@example.test']);});
test('ordinary live lead never includes credit recipient and selects subject',async()=>{const t=transport();await t.adapter.notifyLead({...lead,formType:'contact',route:'/vamos-comecar',fields:{...lead.fields,contactSubject:'Vender'}},{...env,FORMS_DELIVERY_MODE:'live'});assert.deepEqual(t.calls[0].body[0].to,['jrmota@kwportugal.pt']);assert.equal(t.calls[0].body[0].subject,'Novo contato - Vender');assert.match(t.calls[0].body[0].text,/Olá Mota, tens uma nova lead do site:/);assert.match(t.calls[0].body[0].text,/Cumprimentos,\nTiago Freitas/)});
test('partial or empty batch receipt cannot be treated as successful',async()=>{for(const receipt of [{data:[{id:'one'}]},{data:[{id:'one'},{}]},{id:'wrong-format'}]){const t=transport(receipt);await assert.rejects(t.adapter.notifyLead(lead,env),/Incomplete email receipt/);}});
test('property email uses server metadata not visitor supplied title',async()=>{const t=transport();await t.adapter.notifyLead({...lead,formType:'contact',route:'/imoveis/kwpt036155'},env);assert.match(t.calls[0].body[1].text,/KWPT036155/);assert.match(t.calls[0].body[1].text,/https:\/\/joaquimmota.pt\/imoveis\/kwpt036155/);assert.match(t.calls[0].body[1].text,/Apartamento T2/)});
